version: '3.8'
services:
  webapp:
    environment:
      - CONN_STR=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGODB_PORT}/?authSource=admin
      - PORT=5000
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "${WEBAPP_PORT}:5000"
    depends_on:
      - mongodb
      - mlclient

  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    
    # volumes:
      # - type: bind
      #   source: ./data
      #   target: /data/db

  mlclient:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    ports:
      - "${MLCLIENT_PORT}:80"
    environment:
      - PORT=80
      - WEBAPP=http://localhost:${WEBAPP_PORT}
      - DB_NAME=testdb
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGODB_PORT}/?authSource=admin
    depends_on:
      - mongodb
      # mongodb:
      #   condition: service_healthy